"""Deterministic tool compaction on the tools/list path (#199, 0.38.0).

Backends generated by pydantic/FastMCP spell every optional parameter as
``{"anyOf": [X, {"type": "null"}], "default": null}``. Across the lotor
backends that boilerplate was ~54k of 519k schema characters. Three rules:

* ``anyOf [X, {type: null}]`` with ``default: null`` on an OPTIONAL property
  becomes X, hoisted into the property.
* ``default: null`` on any other optional property is dropped.
* ``$schema`` is dropped.

The invariant is that compaction only TIGHTENS: every argument set valid under
the compacted schema is valid under the original. Collapsing the null branch
removes the explicit ``null`` an agent could send, and omitting the property is
still valid because it is not required. The other two rules delete annotations.
``additionalProperties: false`` stays, even though it is the next-largest
boilerplate: dropping it would LOOSEN what the agent reads, and then the agent
could send arguments the backend refuses.

Beside the inputSchema, three fields an agent does not use are dropped
(0.38.0): ``outputSchema`` (34 KB on josui), the top-level ``title`` and
``annotations.title``, which repeat the name. The gateway still validates
results against each backend's own outputSchema, which the backend session
holds (``Backend.validate_output_schema``); only the copy served to the agent
goes.

Compaction runs AFTER ``scan_tool_list``, on the verdict it reached. That is
sound because compaction only deletes keys and values and hoists keys that were
already there, so every string the agent reads was in the judged surface
(``_collect_strings`` walks keys and values alike). The verdict cache keeps its
keys, and turning this on re-judges nothing.
"""

from __future__ import annotations

from typing import Any

MAX_DEPTH = 64
"""Subtrees deeper than this are served as-is rather than recursed into.

A backend controls its schema's nesting; this bounds the walk the way
``_collect_strings`` being iterative bounds the scan.
"""

_NULL_BRANCH = {"type": "null"}
# Tool fields no agent reads: the name says what title says, and results are
# validated here against the backend's own outputSchema.
_UNREAD = frozenset({"outputSchema", "title"})
_SUBSCHEMA_LISTS = ("anyOf", "oneOf", "allOf", "prefixItems")
_SUBSCHEMA_VALUES = ("items", "additionalProperties", "not", "contains")
_SUBSCHEMA_MAPS = ("$defs", "definitions")


def compact_tool(tool: dict[str, Any]) -> dict[str, Any]:
    """The tool with its inputSchema compacted and its unused fields dropped.

    Never mutates ``tool``.
    """
    out = {k: v for k, v in tool.items() if k not in _UNREAD}
    annotations = out.get("annotations")
    if isinstance(annotations, dict) and "title" in annotations:
        rest = {k: v for k, v in annotations.items() if k != "title"}
        out["annotations"] = rest
        if not rest:
            del out["annotations"]
    schema = out.get("inputSchema")
    if isinstance(schema, dict):
        out["inputSchema"] = _compact(schema, 0)
    return out


def _compact(node: Any, depth: int) -> Any:
    """Compact one subschema and everything under it."""
    if depth > MAX_DEPTH:
        return node
    if isinstance(node, list):
        return [_compact(item, depth + 1) for item in node]
    if not isinstance(node, dict):
        return node

    out: dict[str, Any] = {}
    required = node.get("required")
    required_names = set(required) if isinstance(required, list) else set()
    for key, value in node.items():
        if key == "$schema":
            continue
        if key == "properties" and isinstance(value, dict):
            out[key] = {
                name: _compact(_optional(prop) if name not in required_names else prop, depth + 1)
                for name, prop in value.items()
            }
        elif key in _SUBSCHEMA_MAPS and isinstance(value, dict):
            out[key] = {name: _compact(sub, depth + 1) for name, sub in value.items()}
        elif key in _SUBSCHEMA_LISTS or key in _SUBSCHEMA_VALUES:
            out[key] = _compact(value, depth + 1)
        else:
            out[key] = value
    return out


def _optional(prop: Any) -> Any:
    """An optional property without its null default, and its null branch if it has one."""
    if not (isinstance(prop, dict) and "default" in prop and prop["default"] is None):
        return prop
    rest = {k: v for k, v in prop.items() if k != "default"}
    if "anyOf" not in rest:
        return rest
    hoisted = _hoist_non_null(rest)
    return prop if hoisted is None else hoisted


def _hoist_non_null(prop: dict[str, Any]) -> dict[str, Any] | None:
    """``prop`` with its ``anyOf [X, null]`` replaced by X, or None if unsafe.

    Unsafe means any other branch count, no null branch, or X sharing a key
    with the property: hoisting would then overwrite something.
    """
    branches = prop["anyOf"]
    if not isinstance(branches, list) or len(branches) != 2 or _NULL_BRANCH not in branches:
        return None
    other = branches[1] if branches[0] == _NULL_BRANCH else branches[0]
    siblings = {k: v for k, v in prop.items() if k != "anyOf"}
    if not isinstance(other, dict) or other.keys() & siblings.keys():
        return None
    return {**other, **siblings}
